spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sguide-user
    username: postgres
    password: A805131a
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect